version: '3.5'

networks:
  lotti:
    driver: ${APP_NETWORK_DRIVER}

services:
  app:
    platform: ${BUILD_PLATFORM}
    build:
      context: ./app
      args:
        - WORK_DIR=${APP_CODE_PATH_CONTAINER}
        - PHP_VERSION=${PHP_VERSION}
        - COMPOSER_INSTALL=${COMPOSER_INSTALL}
        - NVM_INSTALL=${NVM_INSTALL}
        - NODE_VERSION=${NODE_VERSION}
        - NPM_INSTALL=${NPM_INSTALL}
        - YARN_INSTALL=${YARN_INSTALL}
        - http_proxy
        - https_proxy
        - no_proxy
    volumes:
      - ${APP_CODE_PATH_HOST}:${APP_CODE_PATH_CONTAINER}${APP_CODE_CONTAINER_FLAG}
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
      - ${NGINX_SITES_PATH}:/etc/nginx/sites-available
      - ./app/php/php.ini:/usr/local/etc/php/php.ini
    ports:
      - "${NGINX_HTTP_PORT}:80"
      - "${NGINX_HTTPS_PORT}:443"
    depends_on:
      - mysql
    networks:
      - lotti
  mysql:
    platform: ${BUILD_PLATFORM}
    build:
      context: ./mysql
      args:
        - MYSQL_VERSION=${MYSQL_VERSION}
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - TZ=${APP_TIMEZONE}
    volumes:
      - ${MYSQL_DATA_PATH_HOST}/mysql:/var/lib/mysql
      - ${MYSQL_ENTRYPOINT_INITDB}:/docker-entrypoint-initdb.d
    ports:
      - "${MYSQL_PORT}:3306"
    networks:
      - lotti